media:
  folder: imagens/uploads
  public: imagens/uploads

content:
  - name: produtos
    label: Produtos NutriCode
    type: collection
    folder: content
    extension: md
    format: frontmatter
    slug: '{{title}}'
    fields:
      - name: title
        label: Nome do Suplemento
        type: string
        required: true
      - name: imagem
        label: Imagem do Produto
        type: image
        required: true
      - name: detalhes
        label: Detalhes (Ex: 900g, 60 cápsulas, 30ml)
        type: string
        required: true
      - name: categorias
        label: Categorias (Selecione uma ou mais)
        type: select
        multiple: true
        options:
          - label: Bloqueador de Carboidrato
            value: bloqueador-de-carboidrato
          - label: Ganho de Massa
            value: ganho-de-massa
          - label: Indutor do Sono
            value: indutor-do-sono
          - label: Multivitamínico
            value: multivitaminico
          - label: Pré Treino
            value: pre-treino
          - label: Precursor Hormonal
            value: precursor-hormonal
          - label: Proteína
            value: proteina
          - label: Termogênico
            value: termogenico
      - name: body
        label: Descrição de Vendas (Copy)
        type: rich-text
        required: true
