media: imagens/uploads

content:
  - name: produtos
    label: Produtos NutriCode
    type: collection
    folder: content/produtos
    fields:
      - name: title
        label: Nome do Suplemento
        type: string
        required: true
      - name: image
        label: Imagem
        type: image
        required: true
      - name: detalhes
        label: Detalhes (Ex: 900g, 60 cápsulas, 30ml)
        type: string
        required: true
      - name: categorias
        label: Categorias (Adicione as tags. Ex: ganho-de-massa, proteina)
        type: list
      - name: body
        label: Descrição de Vendas (Copy)
        type: rich-text
        required: true
